
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# do this before all your .NET Core tasks
steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.203' 

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)' 

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'  

  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      projects: IdeasWebApi/IdeasWebApi.csproj
      publishWebProjects: false
      modifyOutputPath: true
      zipAfterPublish: true          

  - task: PublishBuildArtifacts@1

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Visual Studio Enterprise with MSDN(307e5a26-2005-49e7-8de1-ed32008bf357)'
      appType: 'webApp'
      WebAppName: 'sido-webapp'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'